# Generated by Django 4.2 on 2023-04-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="campany",
            new_name="name",
        ),
    ]
